version: '3.4'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    environment:
      - ENV=local
    volumes:
      - ./:/go/src/github.com/Matsushin/qiitan-api
    links:
      - mysql
    command: fresh -c fresh.conf
  nginx:
    build: docker/nginx
    ports:
       - "18080:80"
    links:
        - api
    restart: always
  mysql:
    build: docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: root
    ports:
      - "4306:3306"
  aerospike:
    build: docker/aerospike
    ports:
      - "3000:3000"
