version: 2
jobs:
  ecr-deploy:
    working_directory: ~/go/src/github.com/Matsushin/qiitan-api
    docker:
      - image: circleci/python:2.7-node-browsers
        environment:
          AWS_ID: '518965002790'
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: Build ECR API
          command: |
            docker build -f ./docker/api/Dockerfile  -t qiitan-api_api:$CIRCLE_SHA1 .
      - run:
          ame: TAG ECR API
          command: |
            docker tag qiitan-api_api:$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api_api:$CIRCLE_SHA1
      - run:
          name: Build ECR NGINX
          command: |
            docker build -f ./docker/nginx/Dockerfile  -t qiitan-api_nginx:$CIRCLE_SHA1 .
      - run:
          ame: TAG ECR NGINX
          command: |
            docker tag qiitan-api_nginx:$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api_nginx:$CIRCLE_SHA1
      - run:
          name: Build ECR MYSQL
          command: |
            docker build -f ./docker/mysql/Dockerfile  -t qiitan-api_mysql:$CIRCLE_SHA1 .
      - run:
          ame: TAG ECR MYSQL
          command: |
            docker tag qiitan-api_mysql:$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api_mysql:$CIRCLE_SHA1
      - run:
          name: Build ECR AEROSPIKE
          command: |
            docker build -f ./docker/aerospike/Dockerfile  -t qiitan-api_aerospike:$CIRCLE_SHA1 .
      - run:
          ame: TAG ECR AEROSPIKE
          command: |
            docker tag qiitan-api_aerospike:$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api_aerospike:$CIRCLE_SHA1
      - run:
          name: Deploy
          command: |
            export AWS_DEFAULT_REGION="ap-northeast-1"
            export ECS_TASK_FAMILY_NAME="qiitan-api-task${TARGET}"
            export ECS_CONTAINER_DEFINITION_NAME="qiitan-api-containerX${TARGET}"
            export EXECUTION_ROLE_ARN="arn:aws:iam::$AWS_ID:role/ecsTaskExecutionRole"
            bash ./deploy.sh

# Workflows
workflows:
  version: 2
  ecr-deploy:
    jobs:
      - ecr-deploy:
          filters:
            branches:
              only:
                - master