version: 2
jobs:
  ecr-deploy:
    working_directory: ~/go/src/github.com/Matsushin/qiitan-api
    docker:
      - image: circleci/python:2.7-node-browsers
        environment:
          AWS_ID: 518965002790
    steps:
      - checkout
      # Docker in Docker
      - setup_remote_docker # コレを書くことでDocker上にDockerが立ち上がる
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run: docker build -f ./docker/api/Dockerfile  -t qiitan-api:$CIRCLE_SHA1 .
      - run: docker tag qiitan-api-ecr:$CIRCLE_SHA1 ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api-ecr:$CIRCLE_SHA1
      - run: docker push ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/qiitan-api:$CIRCLE_SHA1
      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            export AWS_DEFAULT_REGION="ap-northeast-1"
            export ECS_TASK_FAMILY_NAME="qiitan-api-task${TARGET}"
            export ECS_CONTAINER_DEFINITION_NAME="qiitan-api-containerX${TARGET}"
            export EXECUTION_ROLE_ARN="arn:aws:iam::$AWS_ID:role/ecsTaskExecutionRole"
            bash ./deploy.sh

# Workflows
workflows:
  version: 2
  ecr-deploy:
    jobs:
      - ecr-deploy:
          filters:
            branches:
              only:
                - master