[aerospike.likerankingdb]
Namespace="test"
Set="testset"
Key="like_ranking"

[aerospike.stockrankingdb]
Namespace="test"
Set="testset"
Key="stock_ranking"

[aerospike.cluster.server]
Host="$AEROSPIKE_HOST"
Port=3000

[mysql]
User = "$DB_USER"
Password = "$DB_PASSWORD"
Port = 3306
Database = "qiitan"
Host = "$DB_HOST"

[updcache]
LikeRankingSec = 300
StockRankingSec = 300