[aerospike.likerankingdb]
Namespace="test"
Set="testset"
Key="like_ranking"

[aerospike.stockrankingdb]
Namespace="test"
Set="testset"
Key="stock_ranking"

[aerospike.server]
Host="aerospike"
Port=3000

[mysql]
User = "root"
Password = ""
Port = 3306
Database = "qiitan_test"
Host = "mysql"

[updcache]
LikeRankingSec = 10
StockRankingSec = 10