[aerospike.likerankingdb]
Namespace="qiitan"
Set="like_ranking"

[aerospike.cluster.server]
Host="$AEROSPIKE_HOST"
Port=3000

[mysql]
User = "$DB_USER"
Password = "$DB_PASSWORD"
Port = 3306
Database = "qiitan_test"
Host = "$DB_HOST"

[updcache]
LikeRankingSec = 10